name: Build release .aab
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11      
      - name: Decrypt keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" > keystore.asc
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch keystore.asc > "${TMP_KEYSTORE_FILE_PATH}"/keystore.jks         
      - name: build signed .aab 
        run: ./gradlew app:bundleRelease
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      - name: Upload .aab artifact
        uses: actions/upload-artifact@v1
        with:
          name: android-template
          path: app/build/outputs/bundle/release/app-release.aab
