name: (Test) Build release .apk from b64
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Decrypt keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" > keystore.jks
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}/keystore"
          mkdir -p "${TMP_KEYSTORE_FILE_PATH}"  # Create the directory if it doesn't exist
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > "${TMP_KEYSTORE_FILE_PATH}/keystore.jks"

#      - name: Upload keystore artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: keystore
#          path: ${{ runner.temp }}/keystore/keystore.jks

      - name: build signed .apk
        run: ./gradlew assembleRelease --stacktrace
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      - name: Upload .aab artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: loops/build/outputs/apk/release/loops-release.apk