name: (Test) Build release .apk from b64
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Decode keystore from base64 string to .jks file
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.jks
          # Remove any existing keystore.jks file to avoid conflicts
          rm -f keystore.jks
          # Move keystore.jks to the root directory
          mv keystore.jks $GITHUB_WORKSPACE/keystore.jks
          
      # - name: Convert keystore from base64 string to .jks file
      #   run: |
      #     echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.jks
      
      - name: build signed .apk
        run: ./gradlew assembleRelease --stacktrace
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
